$files = Get-ChildItem -Path "c:\Users\1167023\Desktop\Jabil\jabil-smart-office-frontend\src\views" -Filter "*.vue"

foreach ($file in $files) {
    Write-Host "Processing: $($file.Name)"
    
    $content = Get-Content $file.FullName -Raw -Encoding UTF8
    
    # 修复常见的乱码问题
    $content = $content -replace "刷新�", "刷新中"
    $content = $content -replace "新增部门", "新增部门"
    $content = $content -replace "请输入部门名�", "请输入部门名称"
    $content = $content -replace "展开图标", "展开图标"
    $content = $content -replace "所属厂�", "所属厂区"
    $content = $content -replace "负责�", "负责人"
    $content = $content -replace "请选择负责�", "请选择负责人"
    $content = $content -replace "保存�", "保存中"
    $content = $content -replace "加载数据失败，请检查后端服�", "加载数据失败，请检查后端服务"
    $content = $content -replace "默认数据", "默认数据"
    $content = $content -replace "采购�", "采购部"
    $content = $content -replace "人力资源�", "人力资源部"
    $content = $content -replace "生产�", "生产部"
    $content = $content -replace "研发�", "研发部"
    $content = $content -replace "质量�", "质量部"
    $content = $content -replace "行政�", "行政部"
    $content = $content -replace "供应�", "供应部"
    $content = $content -replace "系统管理�", "系统管理员"
    $content = $content -replace "厂区管理�", "厂区管理员"
    $content = $content -replace "部门管理�", "部门管理员"
    $content = $content -replace "普通员�", "普通员工"
    $content = $content -replace "确定要删除部门\""\""", "确定要删除部门\""\"""
    $content = $content -replace "组件挂载时加载数据", "组件挂载时加载数据"
    $content = $content -replace "搜索时展开所有厂区，确保搜索结果可见", "搜索时展开所有厂区，确保搜索结果可见"
    $content = $content -replace "重置时恢复默认展开状态", "重置时恢复默认展开状态"
    $content = $content -replace "加载中�", "加载中"
    $content = $content -replace "标签�", "标签栏"
    $content = $content -replace "员工花名�", "员工花名册"
    $content = $content -replace "当前总人�", "当前总人数"
    $content = $content -replace "个级�", "个级别"
    $content = $content -replace "各级别人�", "各级别人数"
    $content = $content -replace "人", "人"
    $content = $content -replace "选择状�", "选择状态"
    $content = $content -replace "状�", "状态"
    $content = $content -replace "用户�", "用户名"
    $content = $content -replace "请输入姓�", "请输入姓名"
    $content = $content -replace "请输入工�", "请输入工号"
    $content = $content -replace "请选择性�", "请选择性别"
    $content = $content -replace "男", "男"
    $content = $content -replace "女", "女"
    $content = $content -replace "请选择级�", "请选择级别"
    $content = $content -replace "请输入岗�", "请输入岗位"
    $content = $content -replace "请输入联系电�", "请输入联系电话"
    $content = $content -replace "实习�", "实习生"
    $content = $content -replace "新增/编辑员工对话�", "新增/编辑员工对话框"
    $content = $content -replace "批量导入对话�", "批量导入对话框"
    $content = $content -replace "模板与用户管理一�", "模板与用户管理一致"
    $content = $content -replace "条数据", "条数据"
    $content = $content -replace "�导入结果", "导入结果"
    $content = $content -replace "失败详情", "失败详情"
    $content = $content -replace "�第", "第"
    $content = $content -replace "条：", "条："
    $content = $content -replace "管理�", "管理员"
    $content = $content -replace "普通员�", "普通员工"
    $content = $content -replace "退出登�", "退出登录"
    $content = $content -replace "确定要退出登录吗�", "确定要退出登录吗？"
    $content = $content -replace "已退出登�", "已退出登录"
    $content = $content -replace "请假待审�", "请假待审批"
    $content = $content -replace "2024�", "2024年"
    $content = $content -replace "�月", "月"
    $content = $content -replace "�日", "日"
    $content = $content -replace "�天", "天"
    $content = $content -replace "10分钟�", "10分钟前"
    $content = $content -replace "30分钟�", "30分钟前"
    $content = $content -replace "2小时�", "2小时前"
    $content = $content -replace "过期料提�", "过期料提醒"
    $content = $content -replace "00�", "00件"
    $content = $content -replace "本月KPI报告已生�", "本月KPI报告已生成"
    $content = $content -replace "包含生产、成本、质量数�", "包含生产、成本、质量数据"
    $content = $content -replace "设置为中�", "设置为中文"
    $content = $content -replace "语�", "语速"
    $content = $content -replace "正弦�", "正弦波"
    $content = $content -replace "播放了新消息提示�", "播放了新消息提示音"
    $content = $content -replace "未读数�", "未读数量"
    $content = $content -replace "旧数量变�", "旧数量变为"
    $content = $content -replace "根据通知类型生成不同的语音提�", "根据通知类型生成不同的语音提示"
    $content = $content -replace "您有一份单据需要接收，请处�", "您有一份单据需要接收，请处理"
    $content = $content -replace "您有一条物料提醒，请处�", "您有一条物料提醒，请处理"
    $content = $content -replace "根据类型跳转到对应页�", "根据类型跳转到对应页面"
    $content = $content -replace "标签页数�", "标签页数据"
    $content = $content -replace "仪表�", "仪表盘"
    $content = $content -replace "工作�", "工作台"
    $content = $content -replace "便捷打印", "便捷打印"
    $content = $content -replace "Cost汇�", "Cost汇总"
    $content = $content -replace "过期料延�", "过期料延期"
    $content = $content -replace "员工花名�", "员工花名册"
    $content = $content -replace "找到当前item的索�", "找到当前item的索引"
    $content = $content -replace "收起其他所有分�", "收起其他所有分组"
    $content = $content -replace "其他分组都收�", "其他分组都收起"
    $content = $content -replace "判断菜单项是否应该显�", "判断菜单项是否应该显示"
    $content = $content -replace "切换标签�", "切换标签页"
    $content = $content -replace "关闭标签�", "关闭标签页"
    $content = $content -replace "处理侧边栏点�", "处理侧边栏点击"
    $content = $content -replace "如果已达到最大数量，不添�", "如果已达到最大数量，不添加"
    $content = $content -replace "添加新标�", "添加新标签"
    $content = $content -replace "跳转到系统公�", "跳转到系统公告"
    $content = $content -replace "初始化未读数�", "初始化未读数量"
    $content = $content -replace "检查点击的元素是否是系统公告按钮或其内部元�", "检查点击的元素是否是系统公告按钮或其内部元素"
    $content = $content -replace "不关闭面�", "不关闭面板"
    $content = $content -replace "移除监听�", "移除监听器"
    $content = $content -replace "页面标题和操作区�", "页面标题和操作区域"
    $content = $content -replace "右边单独展开的卡�", "右边单独展开的卡片"
    $content = $content -replace "菜单项类�", "菜单项类型"
    $content = $content -replace "标签项类�", "标签项类型"
    $content = $content -replace "之前的未读数�", "之前的未读数量"
    $content = $content -replace "播放了新消息提示�", "播放了新消息提示音"
    $content = $content -replace "请输入姓�", "请输入姓名"
    $content = $content -replace "请输入工�", "请输入工号"
    $content = $content -replace "请选择性�", "请选择性别"
    $content = $content -replace "请选择级�", "请选择级别"
    $content = $content -replace "请输入岗�", "请输入岗位"
    $content = $content -replace "请输入联系电�", "请输入联系电话"
    $content = $content -replace "实习�", "实习生"
    $content = $content -replace "模板与用户管理一�", "模板与用户管理一致"
    $content = $content -replace "�数据预览", "数据预览"
    $content = $content -replace "条", "条"
    $content = $content -replace "�导入结果", "导入结果"
    $content = $content -replace "�第", "第"
    $content = $content -replace "创建工作�", "创建工作表"
    $content = $content -replace "解析Excel文件失败，请检查格�", "解析Excel文件失败，请检查格式"
    $content = $content -replace "解析数据并映射字�", "解析数据并映射字段"
    $content = $content -replace "尝试匹配Excel的列�", "尝试匹配Excel的列名"
    $content = $content -replace "员工类型�PL/Jabil�", "员工类型(3PL/Jabil)"
    $content = $content -replace "所属厂�", "所属厂区"
    $content = $content -replace "所属部�", "所属部门"
    
    # 保存修复后的文件
    Set-Content -Path $file.FullName -Value $content -Encoding UTF8 -NoNewline
    
    Write-Host "Fixed: $($file.Name)"
}

Write-Host "All files processed!"
